apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website-ingress
  # IMPORTANT: either omit namespace and let Argo destination namespace apply,
  # or set it to production if you want it in production
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: jerryzhu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-website
                port:
                  number: 80
