import type { EducationItem } from "../types/education"

export const education: EducationItem[] = [
  {
    institution: "University of Waterloo",
    degree: "BMath, Computer Science with co-op",
    dates: "2022 – Apr 2027",
    grade: "3.8",
    logo: "/uwaterloo_logo_black.png",
    activities: [
      "Mathsoc",
      "Computer Science Club",
      "Data Science Club",
      "Math Orientation",
      "Math Grad Ball",
      "Cybersecurity Club",
      "Blockchain Club",
      "Geesehacks",
      "Formula Tech Hacks",
      "Hack The North (Finalist)",
      "Math Endowment Fund",
      "WARG",
      "WAT.AI",
      "WATO",
      "AWS Cloud Club (Captain)",
      "GDSC",
      "Socratica",
      "Tech+",
      "Jam Network",
      "UW Acapella (ICCAs)",
      "TEDxUW",
      "UW Hip Hop",
      "UW Breakers",
      "Haebeat Dance Crew",
      "Cheese Club",
      "Tea Club",
      "UW Improv",
      "Varsity Ultimate Frisbee (Open B)",
      "Table Tennis Club",
      "SERVE Volleyball Club",
      "Intramural referee & Champion",
    ],
    scholarships: [
      "University of Waterloo President's Scholarship of Distinction",
      "Faculty Of Mathematics Promissory Scholarship",
    ],
  },
  {
    institution: "University of Waterloo",
    degree: "Bachelor's degree, Pure Mathematics Joint",
    dates: "Sep 2022 – Apr 2027",
    logo: "/uwaterloo_logo_black.png",
  },
  {
    institution: "University of Waterloo",
    degree: "Bachelor's degree, Combinatorics and Optimization",
    dates: "Sep 2022 – Apr 2027",
    logo: "/uwaterloo_logo_black.png",
  },
  {
    institution: "University of Waterloo",
    degree: "Bachelor's degree, Computational Mathematics",
    dates: "Sep 2022 – Apr 2027",
    logo: "/uwaterloo_logo_black.png",
  },
  {
    institution: "Pierre Elliott Trudeau High School",
    degree: "Ontario Secondary School Diploma, Public High School",
    dates: "2018 – 2022",
    grade: "99.2",
    logo: "/hs_logo.png",
    activities: [
      "Computer Science Club (ECOO provincials)",
      "Mathematica Club (HMMT competitor, PCMM finalist)",
      "Principia",
      "Trubotics (top 16 regionals)",
      "Fairtrade",
      "Concert Band",
      "Science Olympics Team (1st place)",
    ],
  },
]
