import type { ExperienceItem } from "../types/experience"

export const experiences: ExperienceItem[] = [
  {
    title: "Software Engineer",
    company: "StackAdapt",
    location: "Toronto, Ontario, Canada · Remote",
    date: ["Jan 2026", "Present"],
    logo: "/stackadapt-logo.png",
    description: "Internship",
    points: [
      "Built internal dashboards workflows used by analytics teams to target large-scale segment data",
      "Optimized GraphQL queries across Go and Ruby on Rails services, reducing fetch latency by 35%",
      "Designed backend APIs and data models for million record audience segmentation pipelines",
      "Contributed to internal Chrome extension with 60% engineer adoption, improving code ownership visibility",
    ],
    tags: ["Go", "Ruby on Rails", "GraphQL"],
  },
  {
    title: "Software Quality Engineer",
    company: "AfterQuery Experts",
    location: "Remote",
    date: ["Oct 2025", "Dec 2025"],
    logo: "/afterquery-experts-logo.png",
    description: "On-Call",
    points: [
      "Wrote software and audited LLMs for AfterQuery projects contributing to LLM research",
    ],
    tags: ["LLMs"],
  },
  {
    title: "Campus Ambassador",
    company: "AfterQuery",
    location: "San Francisco, California, United States · Remote",
    date: ["Jun 2025", "Oct 2025"],
    logo: "/afterquery-logo.png",
    points: [
      "Worked with clubs to partner with AfterQuery",
      "Used targeted marketing to refer students to AfterQuery projects",
    ],
  },
  {
    title: "Software Engineer",
    company: "Core Flow AI",
    location: "Sydney, New South Wales, Australia · Remote",
    date: ["Jun 2025", "Aug 2025"],
    logo: "/coreflow-logo.png",
    description: "Contract Part-time",
    points: [
      "Built end to end ML models for the entertainment industry",
    ],
    tags: ["TypeScript", "Supabase"],
  },
  {
    title: "Data Engineer",
    company: "Super.com",
    location: "San Francisco, California, United States · Remote",
    date: ["May 2025", "Aug 2025"],
    logo: "/super-logo.png",
    description: "Internship",
    points: [
      "Built/audited 50+ DBT models powering Looker and Redash dashboards, increasing data ingestion integrity by 30%",
      "Led migration of ETL ingestion from Fivetran to Estuary, Snowpipe, and Airflow, improving reliability, maintainability, and contributing to a 10% MRR lift",
      "Reduced analytics and warehouse costs by 20% through Snowflake sharding strategies and HighTouch and Amplitude optimization",
    ],
    tags: ["Data Engineering", "Snowflake", "DBT", "Airflow", "Looker", "Redash"],
  },
  {
    title: "Full Stack Software Engineer",
    company: "Aview International",
    location: "Ancaster, Ontario, Canada · Remote",
    date: ["Aug 2023", "Dec 2024"],
    logo: "/aview-logo.png",
    description: "Internship",
    points: [
      "Pioneered an agentic e2e video distribution pipeline on AWS and GCP, increasing throughput by 8×",
      "Trained a neural TTS dubbing model using NestJS, supporting 30+ languages and serving 100+ users",
      "Reduced North Star KPI costs by 30% through AI editing and automated review flows",
      "Optimized frontend renders through Next.js SSR and CI/CD with Docker and Kubernetes, reducing LCP by 60% and TTFB by 20% with SSE streaming for progressive DOM updates",
    ],
    tags: ["TypeScript", "Next.js", "AWS", "GCP", "NestJS", "Docker", "Kubernetes"],
  },
  {
    title: "DevOps and ML Engineer",
    company: "Aview International",
    location: "Ancaster, Ontario, Canada · Remote",
    date: ["Dec 2022", "Aug 2023"],
    logo: "/aview-logo.png",
    description: "Internship",
    points: [
      "Built DevOps infrastructure and ML pipelines",
    ],
    tags: ["Github Actions", "Ansible", "ML"],
  },
  {
    title: "Content Writer",
    company: "Forem",
    location: "Remote",
    date: ["Sep 2022", "Dec 2024"],
    logo: "/forem-logo.png",
    points: [
      "Tech based content writer at Forem (dev.to) with 400+ followers",
    ],
    tags: ["Python"],
  },
  {
    title: "Data Quality Specialist",
    company: "Shipd",
    location: "Toronto, Ontario, Canada · Remote",
    date: ["Apr 2024", "Oct 2024"],
    logo: "/shipd-logo.png",
    description: "Contract Part-time",
    points: [
      "Curated and solved 500+ competitive programming and software problems for data training",
    ],
  },
  {
    title: "Content Writer",
    company: "Beavr Design",
    location: "Remote",
    date: ["Jun 2023", "Oct 2023"],
    logo: "/beavr-logo.png",
    description: "On-Call",
    points: [
      "Writing technical content articles about agentic AI",
    ],
  },
  {
    title: "DevOps Engineer (SRE)",
    company: "OPENLANE",
    location: "Toronto, Ontario, Canada · Remote",
    date: ["May 2023", "Aug 2023"],
    logo: "/openlane-logo.png",
    description: "Internship",
    points: [
      "Automated 10+ deploy pipelines with Retool, ArgoCD, Terraform, and Azure DevOps CI/CD",
      "Designed an access-elevation system on EKS using Helm and Istio, reducing Orca security alerts by 10% and increasing RBAC test coverage by 30%",
      "Operated Kubernetes backed infra and observability stacks with Splunk, PagerDuty, Honeycomb, and Grafana, resolving 100+ critical incidents, increasing system observability coverage by 40%",
    ],
    tags: ["AWS", "Azure DevOps", "Kubernetes", "Terraform", "ArgoCD", "Helm", "Istio"],
  },
  {
    title: "Software Engineer",
    company: "The Distilling Lab",
    location: "Remote",
    date: ["Feb 2023", "Aug 2023"],
    logo: "/distilling-logo.png",
    description: "Contract Part-time",
    points: [
      "Building tooling for developer orchestration",
    ],
  },
  {
    title: "Software Engineer",
    company: "LineupAppQ",
    location: "New York, New York, United States · Remote",
    date: ["Mar 2023", "Jun 2023"],
    logo: "/lineup-logo.png",
    description: "Internship",
    points: [
      "Built internal tooling for payment processing with a 100+ user application",
      "Optimized frontend SSE architecture and built endpoints for queue management",
    ],
    tags: ["JavaScript", "OOP"],
  },
  {
    title: "Founding Machine Learning Engineer",
    company: "Aviato",
    location: "San Francisco, California, United States · Remote",
    date: ["Dec 2022", "Jun 2023"],
    logo: "/aviato-logo.png",
    description: "Internship",
    points: [
      "Developed a recommendation system as a founding ML engineer using NLP models to predict acquisition metrics with 85% accuracy",
      "Built a semantic search and summarization engine over startup datasets using multi-shot text-to-SQL LLMs with LangChain and Pinecone, improving query latency by 4x",
      "Pioneered a scalable VC data ingestion pipeline aggregating 20+ sources, increasing valid ingested data by 250% using DynamoDB, OpenSearch, Kubernetes scraper fleets, and Rayobyte proxies",
    ],
    tags: ["Text-to-SQL", "LLMOps", "LangChain", "Pinecone", "DynamoDB", "OpenSearch"],
  },
  {
    title: "Blockchain Researcher",
    company: "Pocket Universe",
    location: "Remote",
    date: ["Dec 2022", "Apr 2023"],
    logo: "/pocket-logo.png",
    description: "On-Call",
    points: [
      "Researched wash trading detection for crypto markets",
    ],
    tags: ["Rust", "Solidity"],
  },
  {
    title: "Curriculum Developer Intern",
    company: "Codédex",
    location: "New York, New York, United States · Remote",
    date: ["Oct 2022", "Apr 2023"],
    logo: "/codedex-logo.png",
    description: "Internship",
    points: [
      "Developing Codedex's OG Python curriculum used by 100,000+ active members as a founding intern",
      "Optimized DOM rendering and site data with site-wide auditing, handling 10+ critical bugs",
      "Contributed to user audience scaling with mentorship and content creation, garnering 10k+ views over all platforms",
    ],
  },
  {
    title: "Code Mentor and Content Writer",
    company: "Codédex",
    location: "New York, New York, United States · Remote",
    date: ["Sep 2022", "Dec 2022"],
    logo: "/codedex-logo.png",
    description: "Internship",
    points: [
      "Mentored students and created technical content",
    ],
  },
  {
    title: "Lead Machine Learning Engineer",
    company: "Omdena",
    location: "Remote",
    date: ["Jan 2022", "Apr 2023"],
    logo: "/omdena-logo.png",
    description: "Freelance",
    points: [
      "Lead the AI in child protection project, using NLP to cluster and flag dangerous messages in social media",
      "Pioneered the Sysconverge project, a 2D to 3D pipeline for optimization of energy consumption for real estate markets with CV, reaching 73% accuracy on correctly labelled artifacts",
      "Contributed to the AI-Based Road Inspection System project, building a road inspection model to detect critical faults with 80%+ accuracy",
    ],
    tags: ["Python", "NLP", "Computer Vision", "ML"],
  },
  {
    title: "Machine Learning Engineer",
    company: "Omdena",
    location: "Remote",
    date: ["Jul 2022", "Dec 2022"],
    logo: "/omdena-logo.png",
    description: "Freelance",
    points: [
      "Built ML models for various projects",
    ],
  },
  {
    title: "Lead Software Engineer",
    company: "Sysconverge Inc.",
    location: "Toronto, Ontario, Canada · Remote",
    date: ["Jul 2022", "Mar 2023"],
    logo: "/sysconverge-logo.png",
    description: "Internship",
    points: [
      "Applied SAHI segmentation, CV, and OCR to classify architectural artifacts with 90% accuracy",
      "Led development of a full-stack web application using TypeScript, Tailwind CSS, MongoDB, and C#, automating Ontario Building Code 2D-to-3D modeling workflows",
      "Delivered 100+ automated modeling projects using custom Ladybug XML and custom document intelligence driven workflows",
    ],
    tags: ["C++", "Python", "TypeScript", "MongoDB", "C#", "CV", "OCR"],
  },
  {
    title: "Lead Machine Learning Engineer",
    company: "FruitPunch AI",
    location: "Remote",
    date: ["Dec 2022", "Feb 2023"],
    logo: "/fruitpunch-logo.png",
    description: "Freelance",
    points: [
      "Lead AI for seals team, detecting and classifying endangered seals with 86% accuracy",
      "Contributed to ML pipelines to classify coral reefs for marine biology contexts",
    ],
  },
  {
    title: "Content Writer",
    company: "Deepnote",
    location: "San Francisco, California, United States · Remote",
    date: ["Oct 2022", "Feb 2023"],
    logo: "/deepnote-logo.png",
    description: "On-Call",
    points: [
      "Technical content writing",
    ],
  },
]

