import { Project } from "@/types/projects"

export const projects: Project[] = [
  {
    title: "DAG",
    description: "Decentralized data aggregation across all of machine learning.",
    image: "/projects/dag.png",
    link: "https://devpost.com/software/dag-bvj2ih",
    tags: ["Machine Learning", "Blockchain", "Python"],
    year: "2024",
    winner: true,
    teammates: ["Tanish S", "Justin Lau", "Emma Shi"],
    likes: 5,
  },
  {
    title: "RAIdology",
    description: "Simplifying radiology, one conversation at a time",
    image: "/projects/raidology.png",
    link: "https://devpost.com/software/raidology",
    tags: ["AI", "Healthcare", "NLP"],
    year: "2024",
    winner: true,
    teammates: ["William Wang", "Sujata Thakur", "Skylar Ji"],
    likes: 9,
  },
  {
    title: "Steglib",
    description: "A library for steganography",
    image: "/projects/steglib.png",
    link: "https://devpost.com/software/steglib",
    tags: ["Python", "Security", "Cryptography"],
    year: "2024",
    winner: true,
    teammates: ["Benny Wu", "Avni Arora", "Jacky Liu"],
    likes: 21,
    comments: 2,
  },
  {
    title: "HANQ",
    description: "A new kind of voice assistant. Always listening, zero boundaries, and ready to help.",
    image: "/projects/hanq.png",
    link: "https://devpost.com/software/hanq",
    tags: ["AI", "Voice", "React Native"],
    year: "2024",
    winner: true,
    teammates: ["David Teresi"],
    likes: 6,
  },
  {
    title: "Eve",
    description: "Your personal safety network on campus through real-time alerts on incidents!",
    image: "/projects/eve.png",
    link: "https://devpost.com/software/eve-2vqftn",
    tags: ["React Native", "Firebase", "Maps API"],
    year: "2024",
    winner: true,
    teammates: ["Araf A", "Naman Sonawane", "Alan Liu"],
    likes: 5,
  },
  {
    title: "Everything Calendar",
    description: "Like the everything bagel, but for your day :)",
    image: "/projects/everything-calendar.png",
    link: "https://devpost.com/software/everything-calendar",
    tags: ["React", "Calendar API", "TypeScript"],
    year: "2024",
    teammates: ["Marven Wang", "txxshalott Tam", "Jocelyn Xu"],
  },
  {
    title: "QuadReal Regression Project CxC",
    description: "Using machine learning with PyTorch to predict sensor readings during outages.",
    image: "/projects/quadreal.png",
    link: "https://devpost.com/software/quadreal-regression-project-cxc",
    tags: ["PyTorch", "ML", "Python"],
    year: "2024",
    winner: true,
    teammates: ["Ben Meaker", "Matt Au-Yeung"],
  },
  {
    title: "StudySnitch",
    description: "Keeping you accountable when studying, no matter the cost",
    image: "/projects/studysnitch.png",
    link: "https://devpost.com/software/studysnitch",
    tags: ["React", "Computer Vision", "Firebase"],
    year: "2024",
    winner: true,
    teammates: ["Jane He", "Max Tan", "Ricky Huang"],
    likes: 1,
  },
  {
    title: "EVMElectric",
    description: "Electrifying simple DAO for crowdsourcing charging stations",
    image: "/projects/evmelectric.png",
    link: "https://devpost.com/software/evmelectric",
    tags: ["Solidity", "Web3", "React"],
    year: "2023",
    winner: true,
    likes: 3,
  },
  {
    title: "Disruptive",
    description: "A funding DAO platform for investors to seek out insights and connections from microaquisitions to portfolios",
    image: "/projects/disruptive.png",
    link: "https://devpost.com/software/disruptive-gqok69",
    tags: ["Blockchain", "DAO", "Next.js"],
    year: "2023",
    winner: true,
    teammates: ["Isabelle Huang", "Sophie Luo", "Melika Mir Sajjadi"],
    likes: 4,
  },
  {
    title: "MelodicMind",
    description: "Three steps to help you tackle stress and soothe your mind!",
    image: "/projects/melodicmind.png",
    link: "https://devpost.com/software/melodicmind",
    tags: ["React", "Spotify API", "Mental Health"],
    year: "2023",
    winner: true,
    likes: 1,
  },
  {
    title: "DDrive",
    description: "Driving decentralized file storage to the next level",
    image: "/projects/ddrive.png",
    link: "https://devpost.com/software/ddrive",
    tags: ["IPFS", "React", "Blockchain"],
    year: "2023",
    teammates: ["Ri Hong", "Danny Yang"],
    likes: 2,
  },
  {
    title: "Memory",
    description: "Understanding effortlessly.",
    image: "/projects/memory.png",
    link: "https://devpost.com/software/memory-xmb1tz",
    tags: ["AI", "NLP", "Flask"],
    year: "2023",
    teammates: ["Olivia Chan", "Alex Lu", "Matt Au-Yeung"],
    likes: 4,
    comments: 3,
  },
  {
    title: "EduTracker",
    description: "Fast tracking your education to success",
    image: "/projects/edutracker.png",
    link: "https://devpost.com/software/edutracker",
    tags: ["React", "Firebase", "Education"],
    year: "2022",
    winner: true,
    teammates: ["Jacky Liu", "Jake Z", "Avni Arora"],
    likes: 7,
  },
  {
    title: "iSpotHate",
    description: "Hate speech detection as a service",
    image: "/projects/ispothate.png",
    link: "https://devpost.com/software/ispothate",
    tags: ["NLP", "ML", "Python"],
    year: "2022",
    winner: true,
    teammates: ["Suhaani :)"],
    likes: 15,
    comments: 2,
  },
  {
    title: "Foodwise",
    description: "Eat wise, save the cries.",
    image: "/projects/foodwise.png",
    link: "https://devpost.com/software/foodwise-6t4qde",
    tags: ["React", "Computer Vision", "Sustainability"],
    year: "2022",
    winner: true,
    teammates: ["Avni Arora", "Maggie Liu", "Matthew Shen"],
    likes: 5,
  },
  {
    title: "COVID-BOT-19",
    description: "Delivering efficient, trustworthy and real-time COVID-19 data right to your doorstep",
    image: "/projects/covidbot19.png",
    link: "https://devpost.com/software/covid-bot-19",
    tags: ["Python", "API", "Discord Bot"],
    year: "2021",
    likes: 2,
  },
  {
    title: "Distributed Cryptography",
    description: "Encrypting the future together, a bit at a time.",
    image: "/projects/distributed-crypto.png",
    link: "https://devpost.com/software/distributed-cryptography",
    tags: ["Python", "Cryptography", "Distributed"],
    year: "2021",
    winner: true,
    likes: 6,
  },
  {
    title: "The Weathered Traveller",
    description: "A home away from home for every adventurer.",
    image: "/projects/weathered-traveller.png",
    link: "https://devpost.com/software/the-weathered-traveller",
    tags: ["Java", "API", "Travel"],
    year: "2020",
    teammates: ["Star Xie", "Alex-Li107 Li", "Ryan Lin"],
    likes: 7,
  },
]
